### ISSUE TITLE
image/url bug

### ISSUE THREAD

**Issue by soga93** [fanfare/bogchat#11]
`http://i.asdf.us/im/2b/PbGenerate_1509509664-93_586a699a306a120e1391.gif?v=');alert('fuckyounames');alert('HAXEDBY----http://rhizome.org/hax.png @fruitfly fav this`

so yeah bog takes whatever is before a url and stuff

**Comment by soga93** [comment]
post the code on the bogs to see it in action l8r

**Comment by fanfare** [comment]
thanks, patched
