### ISSUE TITLE
some asshole wont stop talking about his stupid dick

### ISSUE THREAD

**Issue by yvonnie** [fanfare/bogchat#2]
what do we even do about this

chrome, mac os 10.12.6 beta

<img width="239" alt="screen shot 2017-05-26 at 6 31 17 pm" src="https://cloud.githubusercontent.com/assets/28990504/26514716/90045090-4241-11e7-80a0-a03bcfb7cdd0.png">

**Comment by dvvidpw** [comment]
I'm experiencing this issue too.  I'm on Chrome/Windows 10.  Thanks!

**Comment by fanfare** [comment]
basic admin controls and 'zoo' exhibit added in commit 1f7546ea08cf4a5c0add98ac7ce3fd345425c9a5
